pipeline {

    	agent {
        	docker {
            		image 'maven:3.6.1-jdk-8'
            		args '--user root'
        	}
    	}
	
	stages {
		stage('build'){
			steps {
				echo 'Compiling worker app'
				dir('worker'){
					sh 'cat /etc/nsswitch.conf'
					sh 'sudo cat "199.232.192.215 repo.maven.apache.org" >> /etc/hosts'
					sh 'mvn compile'
				}
			}
		}
		
		stage('test'){
                        when {
                                changeset "**/worker/**"
                        }
			steps {
				echo 'Running Unit test on Worker app'
                                dir('worker'){
                                        sh 'mvn clean test'
                                }
			}
		}
		
		stage('package'){
                        when {
                                changeset "**/worker/**"
                        }
			steps {
				echo 'Packaging Worker app'
                                dir('worker'){
                                        sh 'mvn package'
                                }
			}
		}
	}
	
	post {
		always{
			echo 'Build pipeline for worker is complete'
		}

                success{
                        echo 'Build pipeline for worker is successfully complete'
                }

                failure{
                        echo 'Build pipeline for worker is failure'
                }
	}
}
