pipeline {

	agent any
	
	tools {
		maven 'Maven 3.6.1'
	}
	
	stages {
		stage('build'){
			steps {
				echo 'Compiling worker app'
				dir('worker'){
					sh 'mvn compile'
				}
			}
		}
		
		stage('test'){
			steps {
				echo 'Running Unit test on Worker app'
			}
		}
		
		stage('package'){
			steps {
				echo 'Packaging Worker app'
			}
		}
	}
	
	post {
		always{
			echo 'Build pipeline for worker is complete'
		}
	}
}
